# Generated by Django 5.2.14 on 2026-06-02 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('platform', models.CharField(choices=[('django_runtime', 'Django Runtime'), ('copilot_studio', 'Microsoft Copilot Studio'), ('azure_ai_foundry', 'Azure AI Foundry'), ('custom_api', 'Custom API Agent'), ('vendor', 'Vendor Platform'), ('embedded', 'Internal App Embed')], max_length=40)),
                ('business_unit', models.CharField(max_length=80)),
                ('owner', models.CharField(max_length=120)),
                ('technical_owner', models.CharField(max_length=120)),
                ('purpose', models.TextField()),
                ('system_prompt', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('pilot', 'Pilot'), ('production', 'Production'), ('retired', 'Retired')], default='review', max_length=24)),
                ('risk_tier', models.PositiveSmallIntegerField(default=1)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('tool_names', models.JSONField(blank=True, default=list)),
                ('telemetry_enabled', models.BooleanField(default=True)),
                ('monthly_active_users', models.PositiveIntegerField(default=0)),
                ('monthly_runs', models.PositiveIntegerField(default=0)),
                ('monthly_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('satisfaction_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_label', models.CharField(default='demo_user', max_length=120)),
                ('channel', models.CharField(default='web', max_length=40)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=24)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='controlplane.agent')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=80)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='controlplane.agentrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('actor', models.CharField(default='demo_user', max_length=120)),
                ('business_unit', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlplane.agent')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlplane.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
