# Generated by Django 5.2.15 on 2026-06-07 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0007_phase_a_governance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='guardrail_level',
            field=models.CharField(choices=[('off', 'Off — log only, never block'), ('warn', 'Warn — flag finding, continue run'), ('block', 'Block — abort run on HIGH findings')], default='block', help_text='Content guardrail enforcement level for this agent.', max_length=10),
        ),
        migrations.AlterField(
            model_name='approval',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer — read-only across assigned BU'), ('agent_builder', 'Agent Builder — register/edit agents in own BU'), ('agent_approver', 'Agent Approver — approve governance reviews'), ('platform_admin', 'Platform Admin — full cross-tenant access')], default='viewer', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, help_text='Home business unit for tenant scoping. Leave blank for cross-tenant (staff/admin) users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='controlplane.businessunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
