# Generated by Django 5.2.15 on 2026-06-07 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0009_phase_b34_eval_drift'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', models.JSONField(default=list, help_text='Serialised float list from text-embedding-3-small (1536 dims).')),
                ('model_id', models.CharField(default='text-embedding-3-small', max_length=80)),
                ('text_hash', models.CharField(blank=True, help_text='SHA-256 of the embedded text — used to skip unchanged agents.', max_length=64)),
                ('embedded_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='controlplane.agent')),
            ],
            options={
                'ordering': ['-embedded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('connector_type', models.CharField(choices=[('sql', 'SQL Database'), ('rest', 'REST API'), ('graphql', 'GraphQL API')], max_length=12)),
                ('config', models.JSONField(default=dict, help_text='Connection configuration (do not store raw secrets — use env var references).')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_connectors', to='controlplane.businessunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('uploaded_by', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending ingestion'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=12)),
                ('file_type', models.CharField(blank=True, help_text='pdf / docx / txt / md', max_length=10)),
                ('raw_text', models.TextField(blank=True, help_text='Full extracted text (set during ingestion).')),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, help_text='Leave blank for platform-wide documents accessible to all agents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='controlplane.businessunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('vector', models.JSONField(default=list)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='controlplane.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
