# Generated by Django 5.2.15 on 2026-06-07 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0010_phase_c_knowledge_connectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='budget_alert',
            field=models.BooleanField(default=False, help_text='Set by compute_budgets when monthly_cost_usd exceeds budget_usd_monthly.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='budget_usd_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly spend cap in USD. Null = no cap. Checked by compute_budgets command.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.CharField(help_text='YYYY-MM of the breached month.', max_length=7)),
                ('budget_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overage_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to='controlplane.agent')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('agent', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='OtelSpan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=32)),
                ('span_id', models.CharField(max_length=16)),
                ('parent_span_id', models.CharField(blank=True, default='', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('SERVER', 'Server'), ('CLIENT', 'Client'), ('INTERNAL', 'Internal'), ('CONSUMER', 'Consumer'), ('PRODUCER', 'Producer')], default='INTERNAL', max_length=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status_code', models.CharField(default='OK', max_length=12)),
                ('status_message', models.TextField(blank=True, default='')),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('exported', models.BooleanField(default=False, help_text='True once forwarded to an OTLP collector.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spans', to='controlplane.agent')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spans', to='controlplane.agentrun')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['trace_id', 'start_time'], name='controlplan_trace_i_7a1e8c_idx'), models.Index(fields=['agent', 'start_time'], name='controlplan_agent_i_d4a976_idx'), models.Index(fields=['exported'], name='controlplan_exporte_0742ef_idx')],
            },
        ),
    ]
