# Generated by Django 5.2.15 on 2026-06-07 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0011_phase_d_otel_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='controlplane.businessunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('triggered_by', models.CharField(default='system', max_length=120)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Initial inputs passed to the workflow (available as {{inputs.key}}).')),
                ('outputs', models.JSONField(blank=True, default=dict, help_text='Accumulated step outputs: {step_name: {key: value}}.')),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='controlplane.workflow')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.SlugField(max_length=80)),
                ('model_override', models.CharField(blank=True, default='', help_text='Override model for this step (empty = use agent default or model router).', max_length=80)),
                ('system_prompt', models.TextField(blank=True, default='', help_text="System prompt for this step (overrides agent's prompt).")),
                ('input_template', models.TextField(blank=True, default='', help_text='Message template. Use {{outputs.STEP.key}} for upstream refs.')),
                ('depends_on', models.JSONField(blank=True, default=list, help_text='List of step_name strings this step depends on.')),
                ('timeout_seconds', models.PositiveIntegerField(default=120, help_text='Max seconds before this task is marked as timed out.')),
                ('retry_limit', models.PositiveSmallIntegerField(default=0, help_text='Number of automatic retries on failure.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (not execution order — use depends_on).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to='controlplane.agent')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='controlplane.workflow')),
            ],
            options={
                'ordering': ['order', 'step_name'],
                'unique_together': {('workflow', 'step_name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('timed_out', 'Timed out')], default='pending', max_length=12)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('resolved_input', models.TextField(blank=True, default='', help_text='Input message after template substitution.')),
                ('output', models.JSONField(blank=True, default=dict, help_text='Structured output extracted from the agent response.')),
                ('raw_output', models.TextField(blank=True, default='', help_text='Raw agent output text.')),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.OneToOneField(blank=True, help_text='The AgentRun created by the orchestrator for this step.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_task_run', to='controlplane.agentrun')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='controlplane.workflowtask')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='controlplane.workflowrun')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('value', models.JSONField(default=dict)),
                ('written_by', models.CharField(blank=True, help_text='Agent slug or user label that last wrote this entry.', max_length=120)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, entry is stale after this time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to='controlplane.agent')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_entries', to='controlplane.workflowrun')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['workflow_run', 'key'], name='controlplan_workflo_2c3f45_idx'), models.Index(fields=['agent', 'key'], name='controlplan_agent_i_10f18f_idx')],
            },
        ),
    ]
