# Generated by Django 5.2.15 on 2026-06-20 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0014_agent_factory_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToolBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(help_text='Registry tool name exposed to the model.', max_length=80)),
                ('binding_status', models.CharField(choices=[('proposed', 'Proposed'), ('sandbox', 'Sandbox'), ('live', 'Live')], default='proposed', max_length=10)),
                ('operation', models.CharField(blank=True, help_text="Connector operation: sql 'query'; rest 'get'/'post'.", max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Tool parameters (e.g. base path, allowed params). No secrets.')),
                ('description', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_bindings', to='controlplane.agent')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tool_bindings', to=settings.AUTH_USER_MODEL)),
                ('connector', models.ForeignKey(blank=True, help_text='Live target. Null until a real connector is attached.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_bindings', to='controlplane.dataconnector')),
            ],
            options={
                'ordering': ['agent', 'tool_name'],
                'unique_together': {('agent', 'tool_name')},
            },
        ),
    ]
