# Generated by Django 5.2.15 on 2026-07-25 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0015_agenttoolbinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncAgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('submitted', 'Submitted'), ('working', 'Working'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='submitted', max_length=12)),
                ('context_id', models.CharField(blank=True, default='', max_length=120)),
                ('channel', models.CharField(default='a2a', max_length=40)),
                ('submitted_by', models.CharField(default='system', max_length=160)),
                ('input_message', models.TextField()),
                ('output_text', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='controlplane.agent')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_tasks', to='controlplane.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='controlplan_state_c18038_idx')],
            },
        ),
    ]
