# Generated by Django 5.2.15 on 2026-07-25 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0016_asyncagenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttoolbinding',
            name='mcp_tool_name',
            field=models.CharField(blank=True, help_text='Name of the tool on the remote MCP server (may differ from tool_name).', max_length=120),
        ),
        migrations.AlterField(
            model_name='agenttoolbinding',
            name='connector',
            field=models.ForeignKey(blank=True, help_text='Live target for a connector-backed tool. Null for an MCP tool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_bindings', to='controlplane.dataconnector'),
        ),
        migrations.CreateModel(
            name='AgentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_json', models.JSONField(blank=True, default=dict, help_text='The full A2A agent-card document served at the card endpoint.')),
                ('is_published', models.BooleanField(default=False, help_text='Only published cards are discoverable/invocable over A2A.')),
                ('version', models.CharField(blank=True, default='', help_text='Agent.version captured at publish time.', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='a2a_card', to='controlplane.agent')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteMcpServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField(help_text='MCP endpoint. SSRF-guarded on every call.')),
                ('transport', models.CharField(choices=[('http', 'Streamable HTTP'), ('sse', 'HTTP + SSE')], default='http', max_length=8)),
                ('auth_ref', models.CharField(blank=True, help_text='Reference to a secret (e.g. env-var name). NEVER the raw secret.', max_length=200)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('disabled', 'Disabled')], default='registered', max_length=12)),
                ('source', models.CharField(default='manual', help_text='How this server was registered: manual | public_registry | scanner.', max_length=20)),
                ('tool_catalog', models.JSONField(blank=True, default=list, help_text='Cached, normalised tools/list result: [{name, description, input_schema}].')),
                ('catalog_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_servers', to='controlplane.businessunit')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business_unit', 'name')},
            },
        ),
        migrations.AddField(
            model_name='agenttoolbinding',
            name='mcp_server',
            field=models.ForeignKey(blank=True, help_text='Live target for an MCP-backed tool. Null for a connector tool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_bindings', to='controlplane.remotemcpserver'),
        ),
    ]
