# Generated by Django 5.2.15 on 2026-07-25 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0017_agenttoolbinding_mcp_tool_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('first_party_agent', 'First-party agent'), ('external_a2a_agent', 'External A2A agent'), ('mcp_server', 'MCP server')], max_length=24)),
                ('identifier', models.CharField(help_text='Stable key within a kind (agent slug, server slug, external id).', max_length=160)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('protocol', models.CharField(blank=True, default='', help_text="Wire protocol: 'a2a' or 'mcp'.", max_length=8)),
                ('endpoint_url', models.URLField(blank=True, default='')),
                ('domain', models.CharField(blank=True, default='', help_text='Business domain (sales/service/finance/hr…) for broker routing (Phase 4).', max_length=80)),
                ('provider_org', models.CharField(blank=True, default='', max_length=120)),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='Normalised skills/tools: [{id, name, description}].')),
                ('card_json', models.JSONField(blank=True, default=dict)),
                ('governance', models.JSONField(blank=True, default=dict, help_text='Posture copied from the source: {risk_tier, guardrail_level, ...}.')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=8)),
                ('source', models.CharField(default='projection', help_text='How catalogued: projection | manual | scanner.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entries', to='controlplane.agent')),
                ('mcp_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entries', to='controlplane.remotemcpserver')),
            ],
            options={
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='controlplan_kind_ceae49_idx'), models.Index(fields=['domain'], name='controlplan_domain_103e21_idx')],
                'unique_together': {('kind', 'identifier')},
            },
        ),
    ]
