# Generated by Django 5.2.15 on 2026-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0018_registryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryentry',
            name='review_status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text="Scanned entries start 'discovered' and are hidden from agent-facing discovery until approved. Governed sources default 'approved'.", max_length=12),
        ),
    ]
