# Generated by Django 5.2.15 on 2026-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0019_registryentry_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncagenttask',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Execution claims so far; tasks exceeding the max are dead-lettered.'),
        ),
        migrations.AddField(
            model_name='asyncagenttask',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, help_text='Caller-supplied dedup key: a second submit with the same key returns the existing task instead of executing twice.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Execution claims so far; runs exceeding the max are dead-lettered.'),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, help_text='Caller-supplied dedup key: a second enqueue with the same key returns the existing run instead of executing twice.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asyncagenttask',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('working', 'Working'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('dead_letter', 'Dead letter')], default='submitted', max_length=12),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('dead_letter', 'Dead letter')], default='pending', max_length=12),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['status', 'started_at'], name='controlplan_status_818947_idx'),
        ),
        migrations.AddConstraint(
            model_name='asyncagenttask',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uniq_asyncagenttask_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='workflowrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uniq_workflowrun_idempotency_key'),
        ),
    ]
