# Generated by Django 5.2.15 on 2026-07-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0020_production_hardening_dlq_idempotency'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent', 'status', 'started_at'], name='agentrun_agent_status_at'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['started_at'], name='agentrun_started_at'),
        ),
    ]
