# Generated by Django 5.2.15 on 2026-07-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlplane', '0022_apikey_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='evalcase',
            name='judge_prompt',
            field=models.TextField(blank=True, default='', help_text='AI-2: grading criteria for the LLM judge (blank = deterministic only).'),
        ),
        migrations.AddField(
            model_name='evalsuite',
            name='use_llm_judge',
            field=models.BooleanField(default=False, help_text='Grade cases with a judge_prompt via LLM (falls back to deterministic scoring).'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='run_interval_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflow',
            name='webhook_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
